# Challenge 05 (Boss): 完整数据层
# TODO: Repository 模式
class UserRepository:
    def __init__(self, session): ...
    def get(self, id): ...
    def get_by_email(self, email): ...
    def create(self, data): ...
    def update(self, id, data): ...
    def delete(self, id): ...
    def list(self, page, per_page): ...
    def search(self, keyword): ...

class PostRepository:
    # TODO: 同样的 CRUD + 关联查询
    pass
