# Challenge 03: ORM 查询操作
# TODO: 实现以下查询函数
# def get_user_by_id(session, user_id): ...
# def get_users_by_age(session, min_age, max_age): ...
# def create_user(session, username, email): ...
# def update_user_email(session, user_id, new_email): ...
# def delete_user(session, user_id): ...
# def get_user_posts(session, user_id): ...
# def search_posts(session, keyword): ...
# def get_paginated_users(session, page, per_page): ...
