# Prompt管理
# TODO: 实现 PromptManager 类

from __future__ import annotations

# TODO:
# class PromptManager:
#     def __init__(self, system_prompt): ...
#     def register(self, name, template): ...
#     def render(self, name, **kwargs): ...
#     def get_system_message(self) -> dict: ...
